<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="130221" started-at="2021-04-27T11:01:51 IST" finished-at="2021-04-27T11:04:01 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="130221" started-at="2021-04-27T11:01:51 IST" finished-at="2021-04-27T11:04:01 IST">
      <class name="testcases.ib.cards.E2E09_Verify_User_able_to_Reset_Card_Pin">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:testcases.ib.cards.E2E09_Verify_User_able_to_Reset_Card_Pin@33723e30]" name="beforeSuite" is-config="true" duration-ms="91" started-at="2021-04-27T11:01:51 IST" finished-at="2021-04-27T11:01:51 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:testcases.ib.cards.E2E09_Verify_User_able_to_Reset_Card_Pin@33723e30]" name="beforeTest" is-config="true" duration-ms="5" started-at="2021-04-27T11:01:51 IST" finished-at="2021-04-27T11:01:51 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="setData()[pri:0, instance:testcases.ib.cards.E2E09_Verify_User_able_to_Reset_Card_Pin@33723e30]" name="setData" is-config="true" duration-ms="1" started-at="2021-04-27T11:01:51 IST" finished-at="2021-04-27T11:01:51 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setData -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:testcases.ib.cards.E2E09_Verify_User_able_to_Reset_Card_Pin@33723e30]" name="beforeMethod" is-config="true" duration-ms="6587" started-at="2021-04-27T11:01:51 IST" finished-at="2021-04-27T11:01:57 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="verifyAuthScreen()[pri:0, instance:testcases.ib.cards.E2E09_Verify_User_able_to_Reset_Card_Pin@33723e30]" name="verifyAuthScreen" duration-ms="122548" started-at="2021-04-27T11:01:57 IST" finished-at="2021-04-27T11:04:00 IST">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[FAILED]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: FAILED
at utils.Reporter.reportStep(Reporter.java:29)
at wrappers.GenericWrappers.enterByXpath(GenericWrappers.java:425)
at pages.internetBanking.CardsPage.enterPin(CardsPage.java:234)
at testcases.ib.cards.E2E09_Verify_User_able_to_Reset_Card_Pin.verifyAuthScreen(E2E09_Verify_User_able_to_Reset_Card_Pin.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAuthScreen -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:testcases.ib.cards.E2E09_Verify_User_able_to_Reset_Card_Pin@33723e30]" name="afterMethod" is-config="true" duration-ms="1053" started-at="2021-04-27T11:04:00 IST" finished-at="2021-04-27T11:04:01 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:testcases.ib.cards.E2E09_Verify_User_able_to_Reset_Card_Pin@33723e30]" name="afterTest" is-config="true" duration-ms="0" started-at="2021-04-27T11:04:01 IST" finished-at="2021-04-27T11:04:01 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:testcases.ib.cards.E2E09_Verify_User_able_to_Reset_Card_Pin@33723e30]" name="afterSuite" is-config="true" duration-ms="0" started-at="2021-04-27T11:04:01 IST" finished-at="2021-04-27T11:04:01 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- testcases.ib.cards.E2E09_Verify_User_able_to_Reset_Card_Pin -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
