<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-S2KSJTH" name="testcases.QA.admin.customerManagement.E2E02_Verify_User_able_to_Activate_and_Approve_User_Successfully_in_Admin" tests="2" failures="0" timestamp="2021-04-19T14:06:39 IST" time="146.595" errors="1">
  <testcase name="verifyActivateScreen" time="73.911" classname="testcases.QA.admin.customerManagement.E2E02_Verify_User_able_to_Activate_and_Approve_User_Successfully_in_Admin">
    <error type="java.lang.RuntimeException" message="FAILED">
      <![CDATA[java.lang.RuntimeException: FAILED
at utils.Reporter.reportStep(Reporter.java:29)
at wrappers.GenericWrappers.verifyElementisPresent(GenericWrappers.java:1147)
at pages.QA.admin.CustomerManagementPage.SuccessMessage(CustomerManagementPage.java:252)
at testcases.QA.admin.customerManagement.E2E02_Verify_User_able_to_Activate_and_Approve_User_Successfully_in_Admin.verifyActivateScreen(E2E02_Verify_User_able_to_Activate_and_Approve_User_Successfully_in_Admin.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verifyActivateScreen -->
  <system-out/>
  <testcase name="verifyActivateApproveScreen" time="72.684" classname="testcases.QA.admin.customerManagement.E2E02_Verify_User_able_to_Activate_and_Approve_User_Successfully_in_Admin"/>
  <system-out/>
</testsuite> <!-- testcases.QA.admin.customerManagement.E2E02_Verify_User_able_to_Activate_and_Approve_User_Successfully_in_Admin -->
