<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Prabhukrishnan" name="testcases.CIB.Transfers.TC25_Checker_Search_Internal_Payment_in_Manage_List" tests="1" failures="0" timestamp="19 Nov 2020 19:21:53 GMT" time="190.812" errors="1">
  <testcase name="checkerManageListSearch" time="190.812" classname="testcases.CIB.Transfers.TC25_Checker_Search_Internal_Payment_in_Manage_List">
    <error type="java.lang.RuntimeException" message="FAILED">
      <![CDATA[java.lang.RuntimeException: FAILED
	at utils.Reporter.reportStep(Reporter.java:29)
	at wrappers.GenericWrappers.clickWrapper(GenericWrappers.java:335)
	at wrappers.GenericWrappers.clickByXpath(GenericWrappers.java:719)
	at pages.CIBTransferPage.clickProceedToSubmitBtn(CIBTransferPage.java:1239)
	at testcases.CIB.Transfers.TC25_Checker_Search_Internal_Payment_in_Manage_List.createBillPayment(TC25_Checker_Search_Internal_Payment_in_Manage_List.java:50)
	at testcases.CIB.Transfers.TC25_Checker_Search_Internal_Payment_in_Manage_List.checkerManageListSearch(TC25_Checker_Search_Internal_Payment_in_Manage_List.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:663)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:849)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1157)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- checkerManageListSearch -->
</testsuite> <!-- testcases.CIB.Transfers.TC25_Checker_Search_Internal_Payment_in_Manage_List -->
